import {operaClick} from 'common'
import {dataTable} from 'dataTable'
import {treeView} from 'treeview'
import {treeGrid} from 'treeGrid'
const deepCopy = require('common').deepCopy
const operaClickCopy = deepCopy.deepCopy(operaClick)
const dataTableCopy = deepCopy.deepCopy(dataTable)
const treeViewCopy = deepCopy.deepCopy(treeView)
const treeGridCopy = deepCopy.deepCopy(treeGrid)
const AsyncView = require('common').AsyncView
const CommonSelect = require('src/components/common/commonSelect')
